### ISSUE TITLE
Loading norg tree-sitter doesn't work with non-lazy config

### ISSUE THREAD

**Issue by DarkKronicle** [juniorsundar/neorg_extras#22]
There's a step to find ensure the neorg folds.scm is loaded [here](https://github.com/juniorsundar/neorg-extras/blob/2bb76ad18bbb4663f1ae5756a2bbdab551d05f71/lua/neorg/modules/external/many-mans/module.lua#L48). This assumes that all the plugins are installed in the default lazy location, when it can instead be inside any runtimepath (unless there's another variable I'm forgetting).

I think something like this would work:
```lua
local neorg_query = ""
for _, runtime in ipairs(vim.fn.split(vim.api.nvim_get_option("runtimepath"), ",")) do
    local file = runtime .. "/queries/norg/folds.scm"
    if vim.fn.filereadable(file) == 1 then
        neorg_query = table.concat(vim.fn.readfile(file), "\n")
        break
    end
end
if neorg_query == "" then
    vim.api.nvim_err_writeln("Failed to find Neorg Tree-sitter query file in runtimepath")
end
```

**Comment by juniorsundar** [comment]
Is this currently causing issues for your use?

Because depending on how urgent this is I can push a fix for this immediately or this weekend.

**Comment by DarkKronicle** [comment]
It's throwing an error because of my setup :sweat_smile: (tho it seems that mostly everything still works? So not critical). No rush though! A simple push would be fine, I'm just pulling from main anyways. 

This also needs to be tested on a standard lazy setup.

**Comment by juniorsundar** [comment]
You can try two things as a temporary fix while I address this issue:

I think if you set 

```lua
  ["external.many-mans"] = {
config = {
treesitter_fold = false
}
}
```

it won't call this function

Alternatively you can just remove this line from the source code. But try the above first. I added this flag just for these kind of situations. 

https://github.com/juniorsundar/neorg-extras/blob/main/lua/neorg/modules/external/many-mans/module.lua#L32C5-L35C4

**Comment by DarkKronicle** [comment]
The error is gone! Thanks again for your work on this plugin :)

**Comment by juniorsundar** [comment]
@DarkKronicle I have fixed this issue (or at least I think I did). You can checkout to main and verify if the property metadata tags are folding (make sure to set treesitter_fold = true).

**Comment by DarkKronicle** [comment]
No error this time, so I'll take it it works
